const products = [
  {
    id: 1,
    name: "name",
    url: "image/sale1.jpg",
    price: 20,
    sale: true,
    percent: 20,
    collection: "office",
    category: "top",
  },
  {
    id: 2,
    name: "name",
    url: "image/sale2.jpg",
    price: 17,
    sale: true,
    percent: 30,
    collection: "summer",
    category: "top",
  },
  {
    id: 3,
    name: "name",
    url: "image/sale3.jpg",
    price: 25,
    sale: true,
    percent: 25,
    collection: "spring",
    category: "dress",
  },
  {
    id: 4,
    name: "name",
    url: "image/sale4.jpg",
    price: 10,
    sale: true,
    percent: 26,
    collection: "spring",
    category: "dress",
  },
  {
    id: 5,
    name: "name",
    url: "image/sale5.jpg",
    price: 20,
    sale: true,
    percent: 25,
    collection: "spring",
    category: "skirt",
  },
  {
    id: 6,
    name: "name",
    url: "image/sale6.jpg",
    price: 30,
    sale: true,
    percent: 19,
    collection: "office",
    category: "bottom",
  },
  {
    id: 7,
    name: "name",
    url: "image/sale7.jpg",
    price: 25,
    sale: true,
    percent: 22,
    collection: "spring",
    category: "top",
  },
  {
    id: 8,
    name: "name",
    url: "image/sale8.jpg",
    price: 10,
    sale: true,
    percent: 18,
    collection: "spring",
    category: "top",
  },
  {
    id: 9,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2023/04/21/168206403360af84b6cb4efd4e9540d5a44b0314a2_thumbnail_600x.jpg",
    price: 15,
    sale: false,
    percent: null,
    collection: "office",
    category: "skirt",
  },
  {
    id: 10,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2023/04/20/1681960054c885c643f91491dedaa81726519f6e18_thumbnail_600x.jpg",
    price: 11,
    sale: false,
    percent: null,
    collection: "urban",
    category: "skirt",
  },
  {
    id: 11,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2023/02/02/1675302250c32f793240e575ed15272a9d6b4adfc0_thumbnail_600x.jpg",
    price: 13,
    sale: false,
    percent: null,
    collection: "urban",
    category: "dress",
  },
  {
    id: 12,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2023/04/20/1681955847f1e25413ca7e4f88a561fe2f1cda9b50_thumbnail_600x.jpg",
    price: 15,
    sale: false,
    percent: null,
    collection: "summer",
    category: "dress",
  },
  {
    id: 13,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2023/04/20/1681988074105bc0e6e1a237d0b3c016190ed131e0_thumbnail_600x.jpg",
    price: 19,
    sale: false,
    percent: null,
    collection: "office",
    category: "top",
  },
  {
    id: 14,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2022/04/15/16500214656fefdf8786d69224fa8a06d2463a3f89_thumbnail_600x.jpg",
    price: 10,
    sale: false,
    percent: null,
    collection: "urban",
    category: "top",
  },

  {
    id: 15,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2022/07/14/1657774900407e22dc3d32995d1266404f1ccac687_thumbnail_600x.jpg",
    price: 19,
    sale: false,
    percent: null,
    collection: "office",
    category: "bottom",
  },
  {
    id: 16,
    name: "name",
    url: "https://img.ltwebstatic.com/images3_pi/2022/02/10/164447362771f5f7fb71233623a9d360d478e2e023_thumbnail_600x.jpg",
    price: 13,
    sale: false,
    percent: null,
    collection: "summer",
    category: "bottom",
  },
];

const collectionInfo = [
  {
    id: 1,
    collection: "النوع الاول",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi ratione maiores quidem perferendis iure vel adipisci quam recusandae facere, molestiae delectus, odit, aliquid ea aspernatur.",
  },
  {
    id: 2,
    collection: "النوع الثاني",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi ratione maiores quidem perferendis iure vel adipisci quam recusandae facere, molestiae delectus, odit, aliquid ea aspernatur.",
  },
  {
    id: 1,
    collection: "النوع الثالث",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi ratione maiores quidem perferendis iure vel adipisci quam recusandae facere, molestiae delectus, odit, aliquid ea aspernatur.",
  },
  {
    id: 1,
    collection: "النوع الرابع",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi ratione maiores quidem perferendis iure vel adipisci quam recusandae facere, molestiae delectus, odit, aliquid ea aspernatur.",
  },
];
